# Generated by Django 4.2.5 on 2023-09-15 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null='True', related_name='watchlist', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
    ]
