# Generated by Django 4.2.5 on 2023-09-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watclistcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watclistcomments',
            old_name='lisitng',
            new_name='listing',
        ),
    ]
