# Generated by Django 4.2.5 on 2023-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_lisitng_watclistcomments_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatclistComments',
            new_name='WatclistComment',
        ),
    ]
