# Generated by Django 4.2.5 on 2023-09-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_listing_watclistcomment_listingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watclistcomment',
            old_name='listingPage',
            new_name='listing',
        ),
    ]
